export const HOME_ROUTE = "/"
export const TEST_ROUTE = "/test"
export const RANDOM_TEST_ROUTE = "/test?random=true"
export const STATISTICS_ROUTE = "/statistics"
export const CATEGORY_SELECTION_ROUTE = "/category-selection"
